//FETCH ACTION TYPES
export const FETCH_INIT = "FETCH_INIT";
export const FETCH_SUCCESS = "FETCH_SUCCESS ";
export const FETCH_FAILED = "FETCH_FAILED";

export const DELETE_CONTACT = "DELETE_CONTACT";
export const ADD_CONTACT = "ADD_CONTACT";

//MODAL ACTION TYPES
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

//UI ACTION TYPES
export const SET_FETCHED_CONTACTS = "SET_FETCHED_CONTACTS";
